spring:
  application:
    name: trusted-transfer-application
  datasource:
    url: ${PRIMARY_URL}
    username: ${PRIMARY_USER}
    password: ${PRIMARY_PASSWORD}
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: never

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}
  error:
    include-message: never

demo:
  api-token: ${APP_API_TOKEN}
  key-url: ${KEY_SERVICE_URL:http://127.0.0.1:8081}
  writer-token: ${KEY_WRITER_TOKEN}
  processor-url: ${PROCESSOR_URL:http://127.0.0.1:8082}
  processor-token: ${PROCESSOR_APP_TOKEN}
